apiVersion: networking.k8s.io/v1  # Specifies the Kubernetes API version for the Ingress object. In this case, we’re using the “networking.k8s.io/v1” version.
kind: Ingress # Indicates that this YAML configuration defines an Ingress resource.
metadata:
  name: frontend-ingress # assigns the name "frontend-ingress” to this Ingress.
spec:
  rules:
  - host: frontend.example.com # specifies the hostname (domain) for which this Ingress will handle traffic
    http:
      paths:
      - path: / # specifies that requests to the root path (“/”) should be routed to the frontend service
        pathType: Prefix  # indicates that the path matching should be based on a prefix (e.g., “/api” matches “/api/*”)
        backend:
          service:
            name: frontend-service # refers to the Kubernetes Service named "frontend-service”.
            port:
              number: 80 # specifies the port number (80) of the frontend service.
